### ISSUE TITLE
Ontology construct: hasKey

### ISSUE THREAD

**Issue by BlackDark** [VisualDataWeb/OWL2VOWL#11]
Implement the hasKey axiom and export it correctly to the WebVOWL json

**Comment by steffen-l** [comment]
owl:hasKey is semantically similar to owl:InverseFunctionalObjectProperty, so it should also be represented like owl:InverseFunctionalObjectProperty, i.e., simply by adding it in brackets to the property (and likewise listing it in the JSON file) - i.e., same visual representation as transitive, symmetric, functional, etc.
