### ISSUE TITLE
Ontolgy upload bug

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/OWL2VOWL#13]
Depending on the TomCat configuration, the upload of ontologies may not work properly, as the temporal storage of the converted ontologies might not be permitted. We thus need to find an alternative approach, i.e. without temporal storage (which is better anyway for several reasons).

**Comment by linkvt** [comment]
I guess that this has been resolved in https://github.com/VisualDataWeb/OWL2VOWL/issues/10.
