### ISSUE TITLE
Ontology could not be loaded

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/OWL2VOWL#14]
The following ontology generates a strange error: http://tagont.googlecode.com/files/tagont.owl Might be due to the import of other ontologies that are no longer available.

**Comment by BlackDark** [comment]
The problem is because of not available imports: http://www.mindswap.org/ is down

**Comment by steffen-l** [comment]
I assumed that. However, it would still be better if at least an error message is shown in those cases (instead of the loading animation).

**Comment by steffen-l** [comment]
I assumed that. However, the error message "Problems during export happend." is not very informative and helpful though.
