### ISSUE TITLE
Libraries in code

### ISSUE THREAD

**Issue by jmavasa** [VisualDataWeb/OWL2VOWL#21]
Hi ,
How would I use the libraries to do a conversion of an OWLOntology in code and not use the command line. I  looked for ClassImpl.java as I thought it would have an example pointer in the read me file but could not locate it. Any pointers would be appreciated.

Justice

**Comment by BlackDark** [comment]
Hi, if you simply want to convert the ontology into a string you can use [OWL2VOWL.java](https://github.com/VisualDataWeb/OWL2VOWL/blob/master/src/main/java/de/uni_stuttgart/vis/vowl/owl2vowl/Owl2Vowl.java). There you have different possibilities to feed the converter and retrieve the converted ontology in the WebVOWL JSON Format.

**Comment by jmavasa** [comment]
Hi @BlackDark,

Thanks for the pointer, when I tried using the above i get a 
java.lang.NullPointerException: null	at de.uni_stuttgart.vis.vowl.owl2vowl.Owl2Vowl.getJsonAsString(Owl2Vowl.java:41) 

which indicates the convert is null. 

my code is as below 
String s =   new Owl2Vowl(ontology).getJsonAsString();
am passing a owlontology, is there anything i need to do as far as the converter initialisation.
am utilizing the  <dependency>
            <groupId>org.visualdataweb.vowl.owl2vowl</groupId>
            <artifactId>OWL2VOWL</artifactId>
            <version>0.2.1</version>
        </dependency> 

Regards

**Comment by jmavasa** [comment]
I can see version 0.2.1 has that constructor as empty but 0.2.2 has chnaged , will try using the 0.2.2 and feedback
