### ISSUE TITLE
Unconnected datatype nodes

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/OWL2VOWL#23]
There are several unconnected datatypes "flying around" in the NEW* version of OWL2VOWL, which cannot be correct (datatypes are NOT entities with an IRI like classes but always need an accompanying datatype property, i.e., they are ALWAYS linked and never along in VOWL).

For instance, this can be easily seen in FOAF:
http://visualdataweb.de/webvowl/#iri=http://xmlns.com/foaf/0.1/

It was not a problem in the OLD** version of OWL2VOWL:
http://vowl.visualdataweb.org/webvowl/index.html#iri=http://xmlns.com/foaf/0.1/

Other examples showing this problem are GoodRelations (after changing the collapsing level to 0) and OntoViBe:
http://visualdataweb.de/webvowl/#iri=http://purl.org/goodrelations/v1
http://visualdataweb.de/webvowl/#iri=http://ontovibe.visualdataweb.org/

--
* New version = version 0.2.2-snapshot
** Old version = version 0.2.0

**Comment by steffen-l** [comment]
Similar issue appears for owl:Thing - see e.g. http://visualdataweb.de/webvowl/#iri=https://raw.githubusercontent.com/andrewstellman/pbprdf/master/generated/ontology.ttl

owl:Thing nodes should also NEVER "fly around" on their own, but must ALWAYS be connected by properties in VOWL.

**Comment by linkvt** [comment]
The problem with flying datatypes is very likely a WebVOWL bug with equivalent properties, see here http://visualdataweb.de/webvowl/#iri=http://visualdataweb.de/ontobench/ontology/ontology.ttl?features=equivalentprop,equivalentpropdata

**Comment by BlackDark** [comment]
After the fixes in WebVOWL goodrelations and ontovibe are working properly as far as i can see.

In FOAF and the ontology from andrew stellman some constellations results in the free floating literals/things i guess.

- In FOAF we have the <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#InverseFunctionalProperty"/> declarations on datatypeProperties which results in the creation of both a object property and a datatype property in the owlapi and therefore the automation of OWL2VOWL creates always extra nodes and relinks them in the end step. This has to be discussed probably.

- In the ontology of andrew i also found some "misuse" in the declarations. For example we have:
`pbprdf:jumpBallHomePlayer rdfs:label "The home player contesting the jump ball" ;
	rdfs:range pbprdf:Player ;
	rdfs:domain pbprdf:JumpBall ;
	a <http://www.w3.org/2002/07/owl#DatatypeProperty> .`
the declaration for a datatype property. BUT Player and JumpBall are both classes. I am not sure how we should handle such cases.

**Comment by steffen-l** [comment]
I am afraid, but I cannot confirm that the issue is solved in OntoViBe after the WebVOWL fix - there are still unconnected literals, see http://visualdataweb.de/webvowl/#iri=http://ontovibe.visualdataweb.org/ Or do I overlook anything?

**Comment by BlackDark** [comment]
Cache emptied and hard reload of page?

This is my screen:
![image](https://cloud.githubusercontent.com/assets/9947112/20491490/db2f3e6c-b011-11e6-8d83-799a6ca45d8d.png)

**Comment by steffen-l** [comment]
right. my bad. sorry. looks good now.
