### ISSUE TITLE
Wine ontology no longer loaded

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/OWL2VOWL#26]
Compare installation of NEW OWL2VOWL:
http://visualdataweb.de/webvowl/#iri=http://www.w3.org/TR/owl-guide/wine.rdf
with OLD OWL2VOWL:
http://vowl.visualdataweb.org/webvowl/#iri=http://www.w3.org/TR/owl-guide/wine.rdf

While it is visualized in the first, it is not in the second. Instead, the "loading ontology..." message is shown endlessly.

**Comment by BlackDark** [comment]
Bug in OWL2VOWL. The producesWine property has the inverse "hasMaker". HasMaker does not have a domain and range and is in owl2vowl not reference by any other property and therefore not exported to json.
To fix this we have to add any reference (inverse, etc) to the corresponding array of the property.

**Comment by steffen-l** [comment]
Also, other ontologies cannot be loaded with the new version that could be loaded with the old one. The same effect ("loading ontology..." message is shown endlessly), leaving the user with no idea why they cannot be loaded.

Here are some examples (incl. links to the old and new version of OWL2VOWL + WebVOWL):

http://visualdataweb.de/webvowl_new/#iri=http://schema.rdfs.org/all.ttl
http://vowl.visualdataweb.org/webvowl/index.html#iri=http://schema.rdfs.org/all.ttl

http://vowl.visualdataweb.org/webvowl/index.html#iri=http://www.w3.org/2004/02/skos/core
http://visualdataweb.de/webvowl_new/#iri=http://www.w3.org/2004/02/skos/core

**Comment by steffen-l** [comment]
all of the above ontologies are loaded now
