### ISSUE TITLE
Which version of the back end is webvowl 0.5.2 using?

### ISSUE THREAD

**Issue by dscf** [VisualDataWeb/OWL2VOWL#29]
Hi there, 

This is how I did a test:

1.Upload an ontology file to http://vowl.visualdataweb.org/webvowl/index.html and visualize it, and get the json from the convert.php by inspecing chrome dev tool.

2.Download the latest code of this project and convert the same ontology file to json locally

The json in step 1 and step 2 are very different, e.g. the one in step1 has 30 classes, but he one in step2 has 100+ classes.

I assume that the back end of webvowl 0.5.2 is not the latest version of this project. Can I ask which version of the backend it is using?

**Comment by steffen-l** [comment]
Right assumption. The OWL2VOWL converter integrated in the online demo at http://vowl.visualdataweb.org/webvowl/ and linked at http://vowl.visualdataweb.org/webvowl.html is outdated. We replaced it by a completely refactored one last year that supports nearly all OWL 2 concepts. Therefore, the class counts may vary, depending on the ontology. The latest WebVOWL version integrating the new converter is available at http://visualdataweb.de/webvowl/ . We are currently performing last tests and are fixing last issues, but will soon link the new version at http://vowl.visualdataweb.org/webvowl.html (it is just a matter of days).

**Comment by steffen-l** [comment]
This GitHub repository contains the new version of the converter.

**Comment by dscf** [comment]
Thanks for the quick reply seffen. 
I picked to old version(0.5.2) of webvowl because I met some UI issue in the latest one(1.0.0-RC), that's why I was trying to find the matched back end.

I will do more tests to see if I can reproduce it. Please close this ticket. thanks

**Comment by steffen-l** [comment]
I see. Thanks for the update. Note that we further improved the version available at http://visualdataweb.de/webvowl/ recently. However, the OWL2VOWL converter might indeed still contain a few bugs, which are not crucial for the visualization but may render it not as properly. While WebVOWL is already quite mature and stable, the converter is still in a beta state.
