### ISSUE TITLE
Wrong range in OntoVibe

### ISSUE THREAD

**Issue by steffen-l** [VisualDataWeb/OWL2VOWL#3]
The OntoVibe property "dummyProperty" has the range "DisjointClass". However, it currently points to "owl:Thing". This might be because "dummyProperty" is equivalent to "equivalentObjectProperty", the latter having no range (hence "owl:Thing"). The correct range would be the intersection of the ranges of the properties (not the union). Hence, it is similar to a property with two ranges (in this case, one being owl:Thing).

**Comment by BlackDark** [comment]
@linkvt 
Most likely a merge related problem in WebVOWL.

**Comment by linkvt** [comment]
Will be resolved in https://github.com/VisualDataWeb/WebVOWL/issues/28
