### ISSUE TITLE
Maven - JAR generation includes various unneeded deps

### ISSUE THREAD

**Issue by BlackDark** [VisualDataWeb/OWL2VOWL#31]
Currently the maven goal for packaging a JAR file includes all available dependencies. This includes for example:
- spring (springframework, spring boot, etc)
- tomcat
- other http related packages

This is related to the start of the project in which i developed only the JAR archive. At this time we didn't have the focus on the WAR archive and server related stuff.

Possible solution:
Include the maven shade plugin to remove unwanted deps for JAR execution with filter rules.

**Comment by TuanjieLi** [comment]
When I run "mvn clean compile package", the generated jar is only 143K and doesn't include any spring/tomcat related package.

May I ask how you get the JAR including those?

**Comment by BlackDark** [comment]
Check the README:

To build a jar file that can be executed standalone, you have to use the package option with parameter: `mvn package -Denv=standalone` or `mvn package -P standalone-release`

**Comment by TuanjieLi** [comment]
Thanks! Sorry, I didn't notice that it had been in the Instruction file.

**Comment by BlackDark** [comment]
Still not solved
