### ISSUE TITLE
Build additional uberised "*-with-dependencies.jar" file 

### ISSUE THREAD

**Issue by jgrzebyta** [VisualDataWeb/OWL2VOWL#41]
I used jar file available in Maven. After running `java -jar ...` I have error:

```
/data # java -jar /usr/local/lib/OWL2VOWL.jar -file /data/Eve.owl 
no main manifest attribute, in /usr/local/lib/OWL2VOWL.jar
```

I found the reason. I just should re-compile file myself with `standalone-release` profile. It would be helpful if `*_-with-dependencies.jar` was built as well.

**Comment by vitalis-wiens** [comment]
Hi, use the mvn standalone release build and start the ...-shadded.jar
Then it should work

Best regards Vitalis

Am 08.09.2017 3:33 nachm. schrieb "Jacek Grzebyta" <notifications@github.com

**Comment by BlackDark** [comment]
Updated the [README](https://github.com/VisualDataWeb/OWL2VOWL/blob/master/README.md#build-the-jar)

**Comment by BlackDark** [comment]
Is available like described -> Done
