### ISSUE TITLE
New Version 0.3.4

### ISSUE THREAD

**Issue by lmaag182** [VisualDataWeb/OWL2VOWL#46]
There seems to be a newer version around than 0.3.3, as the server version packs 0.3.4. If I compile this I get 0.3.3? How can i get 0.3.4?

**Comment by BlackDark** [comment]
Just a issue with the tag:
https://github.com/VisualDataWeb/OWL2VOWL/commit/003cf6ac6e9894a17e7483f0ff1daddb758fd99d
