### ISSUE TITLE
Add option to ignore external dependencies.

### ISSUE THREAD

**Issue by qurben** [VisualDataWeb/OWL2VOWL#48]
I am trying to convert an ontology with owl2vowl. This ontology has several dependencies, and these dependencies have even more dependencies. I have not yet been able to figure out how to order the dependencies properly.

In ProtegéVOWL dependencies are not loaded when displaying an ontology.

Right now when I try to convert the ontology owl2vowl tries to download the dependencies, but these urls do not exist.

I would like to be able to convert this ontology without all it's dependencies, to just get a visual impression of what is in this single file.

**Comment by vitalis-wiens** [comment]
We are currently working on the import issue, it should be fixed soon 

As a workaround for now you could try to remove manually the imports in your ontology file

Kind Regards

**Comment by vitalis-wiens** [comment]
We have added a missing import handler that omits dependencies that can not be resolved ( not existing urls)
