### ISSUE TITLE
Can you provide the json data generated by vowl to be converted into Ontology objects?

### ISSUE THREAD

**Issue by bingbingll** [VisualDataWeb/OWL2VOWL#53]
How can the json data submitted by WebVOWL be converted into Ontology objects in how OWL2VOWL?

**Comment by Subjekt2Change** [comment]
I have the same question.

I am coding an application wich edits simple ontologies and i am using this API to get the json of an ontology so that my react app can read it.

This works marvelous, however i have problems finding out if the process can be reversed once i am done editing the ontology?

**Comment by vitalis-wiens** [comment]
Hi, 
have we have a basic implementation for this in WebVOWL Editor.
You can find it in the exportTTLModule.js 

It takes the visual representation and creates the ontology.

Cheers Vitalis

**Comment by Subjekt2Change** [comment]
Hi @vitalis-wiens,

thank you very much for your quick answer!

It even is a JavaScript module! That is perfect! I suppose the OWL2VOWL is not yet realised as a js module? This would simplify my implementation, as there would be no need for a backend server that hosts your API. Or is there a public server that already hosts the API? You do not have to answer this question, as is it not part of this issue, i am just curious ;D.

Thank you for answering the question, if i have understood it the right way this should also have answered the question of @bingbingll. So i think this issue can be closed?

Regards,
Subject2Change
