### ISSUE TITLE
Inconsistent releases

### ISSUE THREAD

**Issue by dgarijo** [VisualDataWeb/OWL2VOWL#56]
I have noticed that while this repository lists `v0.3.5` as the most recent, the main page (http://vowl.visualdataweb.org/webvowl.html#linking) lists `v0.3.7` as the latest. Where can someone get `v0.3.7` through maven support?

**Comment by vitalis-wiens** [comment]
Hi, thanks for pointing to the inconsistency.

I have updated the tag and the release version to 0.3.7 

Not exactly sure about maven support

**Comment by dgarijo** [comment]
It's already done through jitpack. Closing issue. Thanks!
