### ISSUE TITLE
OWL2VOWL can't be used from command line

### ISSUE THREAD

**Issue by linkvt** [VisualDataWeb/OWL2VOWL#7]
The maven version 0.2.1 and the local snapshot give the following error: `kein Hauptmanifestattribut, in OWL2VOWL-0.2.2-SNAPSHOT.jar`

**Comment by BlackDark** [comment]
Under work on [Architecture change branch](https://github.com/VisualDataWeb/OWL2VOWL/tree/architecture_change)

**Comment by BlackDark** [comment]
Maven versions are just libraries and not standalone releases.
For standalone look at the github release section [Releases](https://github.com/VisualDataWeb/OWL2VOWL/releases)
